/*
 *
 * FormNasabah constants
 *
 */

export const DEFAULT_ACTION = 'app/FormNasabah/DEFAULT_ACTION';
export const CHANGE_FULLNAME_ACTION = 'app/FormNasabah/CHANGE_FULLNAME_ACTION';
export const CHANGE_BIRTHPLACE_ACTION = 'app/FormNasabah/CHANGE_BIRTHPLACE_ACTION';
export const CHANGE_BIRTHDATE_ACTION = 'app/FormNasabah/CHANGE_BIRTHDATE_ACTION';
export const CHANGE_ADDRESS_ACTION = 'app/FormNasabah/CHANGE_ADDRESS_ACTION';
export const CHANGE_GENDER_ACTION = 'app/FormNasabah/CHANGE_GENDER_ACTION';
export const VALIDATE_INPUT_ACTION = 'app/FormNasabah/VALIDATE_INPUT_ACTION';
export const CHANGE_VALIDATION_MESSAGE_ACTION = 'app/FormNasabah/CHANGE_VALIDATION_MESSAGE_ACTION';
export const CHANGE_TRIGGERED_ACTION = 'app/FormNasabah/CHANGE_TRIGGERED_ACTION';
