export const SET_AUTH_TOKEN_ACTION = 'App/SET_AUTH_TOKEN_ACTION';
export const REMOVE_AUTH_TOKEN_ACTION = 'App/REMOVE_AUTH_TOKEN_ACTION';

export const SET_TOKEN_VERIFIKASI_ACTION = 'App/SET_TOKEN_VERIFIKASI_ACTION';
export const REMOVE_TOKEN_VERIFIKASI_ACTION =
  'App/REMOVE_TOKEN_VERIFIKASI_ACTION';

export const SET_NIK_ACTION = 'App/SET_NIK_ACTION';
export const SET_EMAIL_ACTION = 'App/SET_EMAIL_ACTION';
export const SET_NOTELP_ACTION = 'App/SET_NOTELP_ACTION';
